# 通用配置
conn_max_idle: 10 # 连接池最大空闲连接数
conn_max_open: 100 # 连接池最大连接数
conn_max_lifetime: 1h # 连接数最大生命周期
protocol: tcp # 传输协议
loc: Local # 时区

# 默认数据源配置 支持配置多个数据源
default: 
    driver: mysql
    host: localhost
    port: 3306
    database: victor
    username: root
    password: "yy6689990"  # env(DB_PASSWORD) 支持使用环境变量
    charset: utf8mb4
    collation: utf8mb4_general_ci