connections:
  - ssh.ali
remote_folder: /root/go/project/

backend:
  goos: linux
  goarch: amd64
#   pre_action:
#     - rm /root/go/project/ygo || ture
  post_action:
    - chmod 777 /root/go/project/ygo
    - /root/go/project/ygo app restart
