connections:
  - ssh.ali
remote_folder: /root/go/project/

backend:
  goos: linux
  goarch: amd64
  pre_action:
    - rm /root/go/project/ygo || true
  post_action:
    - chmod 777 /root/go/project/ygo
    - cd /root/go/project && ./ygo app restart
