connections: # 要自动化部署的连接
    - ssh.ali

remote_folder: "/root/go/project/"  # 远端的部署文件夹


backend: # 后端部署配置
    goos: linux # 部署目标操作系统
    goarch: amd64 # 部署目标cpu架构
    pre_action: # 部署前置命令
        - "rm /root/go/project/ygo"
    post_action: # 部署后置命令
        - "chmod 777 /root/go/project/ygo"
        - "/root/go/project/ygo app restart"
