address: 8888

domain: "http://47.92.132.42:8888/"

jwt:
    secret_signature: "ygo_secret"
    issuer: "ygo"
    token_expire_duration: "24h"
    auth_header_key: "authHeader"
    session_key: "userId"

smtp:
    host: "smtp.163.com" # 需要开启smtp能力的邮箱服务
    port: 25
    from: "victor19941115@163.com"
    username: "victor19941115@163.com"
    password: env(SMTP_PASSWORD)